// Shared product catalog data — no client/server directives
// This file is safe to import from both Server Components and Client Components

export const PRODUCTS_CATALOG = [
  {
    id: "hydra-foam-cleanser",
    name: "HYDRA-FOAM CLEANSER",
    subtitle: "Age-Defying, Gentle Hydration Support, + 0.5% PDRN & Hyaluronic Acid",
    priceUSD: 40.71856,
    image: "/model.png",
    hoverImage: "/products/texture-gel.png",
    specifications: JSON.stringify([
      { key: "Brand", value: "BODYBARREL" },
      { key: "Product Type", value: "Age-Defying Hydra-Foam Cleanser" },
      { key: "Volume", value: "100 ml (3.38 fl. oz.)" },
      { key: "Target Audience", value: "All Genders" },
      { key: "Skin Type", value: "Dry, Sensitive & Barrier Depleted" },
      { key: "Primary Benefits", value: "Deep Moisture, Gentle Impurity Removal, Lipid Barrier Support" },
      { key: "Texture", value: "Lightweight Micro-Bubble Foam" },
      { key: "Fragrance", value: "Fragrance-Free (Pure Botanical)" },
      { key: "Usage", value: "Pump 1-2 times onto damp hands, massage onto face in circular motions, rinse thoroughly with warm water." },
      { key: "Recommended Use", value: "Daily (Morning & Evening)" },
      { key: "Free From", value: "Parabens, Sulfates, Mineral Oil, Synthetic Dyes" },
    ]),
  },
  {
    id: "hydra-nutrition-essence",
    name: "HYDRA-NUTRITION ESSENCE",
    subtitle: "Moisture, Nourish + PDRN (Salmon DNA) & Multi-Peptide",
    priceUSD: 75.4491,
    image: "/serum.png",
    hoverImage: "/products/cream-texture.png",
    specifications: JSON.stringify([
      { key: "Brand", value: "BODYBARREL" },
      { key: "Product Type", value: "Cellular Nutrition Essence" },
      { key: "Volume", value: "30 ml (1.01 fl. oz.)" },
      { key: "Target Audience", value: "All Genders" },
      { key: "Skin Type", value: "Dry & Mature Skin" },
      { key: "Primary Benefits", value: "Intense Hydration, Salmon PDRN DNA & Multi-Peptide Repair" },
      { key: "Texture", value: "Concentrated Hydration Serum Gel" },
      { key: "Fragrance", value: "Subtle Herbal & Botanical Hydro-Notes" },
      { key: "Usage", value: "Dispense 3-4 drops after cleansing. Pat gently over face and neck until fully absorbed." },
      { key: "Recommended Use", value: "Twice Daily" },
      { key: "Free From", value: "Parabens, Mineral Oil, Sulfates, Alcohol" },
    ]),
  },
  {
    id: "men-body-wash",
    name: "Derm-Restore Men's Body Wash",
    subtitle: "Deep Cleanse & Lipid Barrier Repair 400ml",
    priceUSD: 38,
    image: "/products/men-wash.png",
    hoverImage: "/products/texture-gel.png",
    specifications: JSON.stringify([
      { key: "Brand", value: "BODYBARREL" },
      { key: "Product Type", value: "Premium Body Wash" },
      { key: "Volume", value: "400 ml (13.5 fl. oz.)" },
      { key: "Target Audience", value: "Men" },
      { key: "Skin Type", value: "All Skin Types" },
      { key: "Primary Benefits", value: "Deep Cleansing, Hydration, Long-Lasting Freshness, Anti-Tan Care" },
      { key: "Texture", value: "Rich Foaming Gel" },
      { key: "Fragrance", value: "Warm Amber & Woody Notes" },
      { key: "Usage", value: "Apply to wet skin, massage into a rich lather, then rinse thoroughly." },
      { key: "Recommended Use", value: "Daily" },
      { key: "Free From", value: "Parabens, Mineral Oil, Sulfates" },
    ]),
  },
  {
    id: "women-body-wash",
    name: "Aura-Glow Women's Body Wash",
    subtitle: "Cellular Recovery & Intense Hydration 400ml",
    priceUSD: 42,
    image: "/products/women-wash.png",
    hoverImage: "/products/texture-gel.png",
    specifications: JSON.stringify([
      { key: "Brand", value: "BODYBARREL" },
      { key: "Product Type", value: "Cellular Recovery Body Wash" },
      { key: "Volume", value: "400 ml (13.5 fl. oz.)" },
      { key: "Target Audience", value: "Women" },
      { key: "Skin Type", value: "Sensitive & Depleted Barrier" },
      { key: "Primary Benefits", value: "Intense Hydration, Cellular Speed & Collagen Support" },
      { key: "Texture", value: "Velvet Moisture Lotion Gel" },
      { key: "Fragrance", value: "Rose Hydrosol & Botanical Bloom" },
      { key: "Usage", value: "Apply onto wet body skin, massage gently into lather, then rinse with lukewarm water." },
      { key: "Recommended Use", value: "Daily" },
      { key: "Free From", value: "Sulfates, Parabens, Silicones, Synthetic Colorants" },
    ]),
  },
  {
    id: "unisex-body-wash",
    name: "Bio-Fit Unisex Body Wash",
    subtitle: "Universal Amino Acid Cleanse 400ml",
    priceUSD: 36,
    image: "/products/unisex-wash.png",
    hoverImage: "/products/texture-gel.png",
    specifications: JSON.stringify([
      { key: "Brand", value: "BODYBARREL" },
      { key: "Product Type", value: "Universal Amino Acid Body Wash" },
      { key: "Volume", value: "400 ml (13.5 fl. oz.)" },
      { key: "Target Audience", value: "Unisex" },
      { key: "Skin Type", value: "All Skin Profiles" },
      { key: "Primary Benefits", value: "Universal Cleansing, Barrier Support & Hydration" },
      { key: "Texture", value: "Silky Hydration Gel" },
      { key: "Fragrance", value: "Clean Marine & Fresh Botanical" },
      { key: "Usage", value: "Lather 2-3 pumps onto wet skin, massage thoroughly and rinse." },
      { key: "Recommended Use", value: "Daily" },
      { key: "Free From", value: "Parabens, Sulfates, Mineral Oil" },
    ]),
  },
  {
    id: "exfoliating-body-wash",
    name: "Dermal-Micro Exfoliating Wash",
    subtitle: "Cellular Resurfacing Body Gel 300ml",
    priceUSD: 40,
    image: "/products/exfoliating-wash.png",
    hoverImage: "/products/texture-gel.png",
    specifications: JSON.stringify([
      { key: "Brand", value: "BODYBARREL" },
      { key: "Product Type", value: "Dermal-Micro Exfoliating Wash" },
      { key: "Volume", value: "300 ml (10.14 fl. oz.)" },
      { key: "Target Audience", value: "All Genders" },
      { key: "Skin Type", value: "Rough & Textured Skin" },
      { key: "Primary Benefits", value: "Cellular Resurfacing, Roughness Smoothing, Keratin Dissolution" },
      { key: "Texture", value: "Micro-Grain Exfoliating Gel" },
      { key: "Fragrance", value: "Refreshing Citrus & Mint" },
      { key: "Usage", value: "Massage gently onto wet skin focusing on rough areas like elbows and knees. Rinse well." },
      { key: "Recommended Use", value: "2-3 Times per Week" },
      { key: "Free From", value: "Parabens, Microplastics, Harsh Acids" },
    ]),
  },
];
