"use client";

import { useState } from "react";
import Nav from "@/components/Nav";
import Footer from "@/components/Footer";
import { User, ShoppingBag, MapPin, Compass, ShieldCheck } from "lucide-react";

export default function AccountPage() {
  const [activeTab, setActiveTab] = useState("regimen");

  const menuItems = [
    { id: "regimen", label: "My Skin Regimen", icon: Compass },
    { id: "orders", label: "Order History", icon: ShoppingBag },
    { id: "profile", label: "Profile Settings", icon: User },
    { id: "addresses", label: "Shipping Addresses", icon: MapPin },
  ];

  // Mock Active Skin Regimen data
  const activeRegimen = [
    { step: "01", name: "Barrier Cleansing Gel", frequency: "Morning & Night", note: "Apply on damp face, massage for 60 seconds." },
    { step: "02", name: "Eye Fitness Serum", frequency: "Morning & Night", note: "Gently pat around the orbital bone until absorbed." },
    { step: "03", name: "Active Recovery Cream", frequency: "Nightly", note: "Warm a pea-sized amount between palms and press into skin." }
  ];

  // Mock Order history data
  const mockOrders = [
    { orderId: "#BB-20984", date: "June 12, 2026", status: "Delivered", totalUSD: 195.0, items: "Active Recovery Cream x1, Eye Fitness Serum x1" },
    { orderId: "#BB-19827", date: "April 28, 2026", status: "Delivered", totalUSD: 65.0, items: "Phyto-Stem Glow Mist x1" }
  ];

  return (
    <>
      <Nav />
      <main className="bg-bg text-ink min-h-screen pt-32 pb-24 font-sans">
        <div className="max-w-7xl mx-auto px-6 md:px-12 grid grid-cols-1 lg:grid-cols-12 gap-12 items-start">
          
          {/* Sidebar Tabs Controls */}
          <div className="lg:col-span-4 bg-card-bg/60 backdrop-blur border border-line/60 rounded-2xl p-6 space-y-6">
            <div className="flex items-center gap-4 pb-6 border-b border-line">
              <div className="w-12 h-12 bg-accent rounded-full flex items-center justify-center text-bg font-display font-semibold text-lg select-none">
                JD
              </div>
              <div>
                <h2 className="font-display font-semibold text-base uppercase text-ink">Jane Doe</h2>
                <span className="text-[10px] text-muted tracking-wider uppercase">Cell-Fit Member since 2026</span>
              </div>
            </div>
            
            <nav className="flex flex-col space-y-2">
              {menuItems.map((item) => {
                const Icon = item.icon;
                return (
                  <button
                    key={item.id}
                    onClick={() => setActiveTab(item.id)}
                    className={`w-full flex items-center gap-3 px-4 py-3 text-xs font-semibold tracking-wider uppercase rounded-xl transition-all duration-200 ${
                      activeTab === item.id
                        ? "bg-bg text-accent border border-line shadow-sm"
                        : "bg-transparent text-ink/70 border border-transparent hover:text-ink hover:bg-bg/40"
                    }`}
                  >
                    <Icon className="w-4.5 h-4.5 text-accent shrink-0" />
                    <span>{item.label}</span>
                  </button>
                );
              })}
            </nav>
          </div>

          {/* Account Detail Display Panels */}
          <div className="lg:col-span-8 bg-card-bg/35 backdrop-blur border border-line/50 rounded-2xl p-8 min-h-[480px]">
            {activeTab === "regimen" && (
              <div className="space-y-8 animate-fadeIn">
                <div className="border-b border-line pb-4">
                  <h3 className="font-display font-semibold text-lg uppercase text-ink">Active Skin Fitness Regimen</h3>
                  <p className="text-xs text-muted mt-1">Custom cellular repair workflow generated by your skin scientists.</p>
                </div>
                
                <div className="space-y-6">
                  {activeRegimen.map((reg) => (
                    <div key={reg.step} className="flex gap-6 pb-6 border-b border-line/55 last:border-0 last:pb-0">
                      <span className="font-display font-bold text-2xl text-accent/50">{reg.step}</span>
                      <div className="space-y-1">
                        <div className="flex items-center gap-3">
                          <h4 className="font-display font-semibold text-sm uppercase text-ink">{reg.name}</h4>
                          <span className="text-[9px] bg-accent/15 text-accent px-2 py-0.5 rounded-full font-bold uppercase tracking-wider">{reg.frequency}</span>
                        </div>
                        <p className="text-xs text-muted">{reg.note}</p>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {activeTab === "orders" && (
              <div className="space-y-8 animate-fadeIn">
                <div className="border-b border-line pb-4">
                  <h3 className="font-display font-semibold text-lg uppercase text-ink">Purchase History</h3>
                  <p className="text-xs text-muted mt-1">Review orders and track delivery statuses.</p>
                </div>

                <div className="space-y-6">
                  {mockOrders.map((order) => (
                    <div key={order.orderId} className="border border-line/70 rounded-xl p-5 bg-bg/50 space-y-4 hover:border-accent/40 transition-colors">
                      <div className="flex items-center justify-between text-xs border-b border-line/45 pb-3">
                        <span className="font-bold text-ink uppercase tracking-wider">{order.orderId}</span>
                        <span className="text-muted">{order.date}</span>
                      </div>
                      <div className="flex items-start justify-between">
                        <div className="space-y-1">
                          <p className="text-xs text-ink/80 font-medium">{order.items}</p>
                          <span className="inline-block text-[9px] font-semibold text-emerald-600 bg-emerald-50 px-2.5 py-0.5 rounded-full tracking-widest uppercase mt-2">
                            {order.status}
                          </span>
                        </div>
                        <span className="text-sm font-semibold text-ink">${order.totalUSD.toFixed(2)}</span>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {activeTab === "profile" && (
              <div className="space-y-8 animate-fadeIn">
                <div className="border-b border-line pb-4">
                  <h3 className="font-display font-semibold text-lg uppercase text-ink">Personal Information</h3>
                  <p className="text-xs text-muted mt-1">Update profile details and communication settings.</p>
                </div>

                <form className="grid grid-cols-1 sm:grid-cols-2 gap-6" onSubmit={(e) => e.preventDefault()}>
                  <div className="space-y-2">
                    <label className="text-[10px] uppercase tracking-widest font-semibold text-ink/75 block">First Name</label>
                    <input type="text" defaultValue="Jane" className="w-full bg-bg border border-line rounded-xl px-4 py-3 text-xs uppercase tracking-wider focus:outline-none focus:border-accent" />
                  </div>
                  <div className="space-y-2">
                    <label className="text-[10px] uppercase tracking-widest font-semibold text-ink/75 block">Last Name</label>
                    <input type="text" defaultValue="Doe" className="w-full bg-bg border border-line rounded-xl px-4 py-3 text-xs uppercase tracking-wider focus:outline-none focus:border-accent" />
                  </div>
                  <div className="space-y-2 sm:col-span-2">
                    <label className="text-[10px] uppercase tracking-widest font-semibold text-ink/75 block">Email Address</label>
                    <input type="email" defaultValue="jane.doe@gmail.com" className="w-full bg-bg border border-line rounded-xl px-4 py-3 text-xs tracking-wider focus:outline-none focus:border-accent" />
                  </div>
                  
                  <div className="sm:col-span-2 pt-4">
                    <button type="submit" className="px-8 py-3.5 bg-ink text-bg text-[10px] font-semibold tracking-widest uppercase hover:bg-accent transition-colors duration-300">
                      Save Changes
                    </button>
                  </div>
                </form>
              </div>
            )}

            {activeTab === "addresses" && (
              <div className="space-y-8 animate-fadeIn">
                <div className="border-b border-line pb-4">
                  <h3 className="font-display font-semibold text-lg uppercase text-ink">Delivery Addresses</h3>
                  <p className="text-xs text-muted mt-1">Manage physical shipping locations.</p>
                </div>

                <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
                  <div className="border border-line rounded-xl p-5 bg-bg/50 relative hover:border-accent/40 transition-all">
                    <span className="text-[9px] bg-accent text-bg px-2.5 py-0.5 rounded-full font-bold uppercase tracking-wider absolute top-4 right-4">Default</span>
                    <h4 className="font-display font-semibold text-xs text-ink uppercase mb-3">Primary Residence</h4>
                    <p className="text-xs text-muted leading-relaxed">
                      Jane Doe <br />
                      104 Mercer Street, Floor 3 <br />
                      New York, NY 10012 <br />
                      United States
                    </p>
                  </div>
                  <div className="border border-dashed border-line rounded-xl p-5 flex flex-col items-center justify-center text-center cursor-pointer hover:border-accent transition-colors min-h-[140px]">
                    <span className="text-xs font-semibold text-accent uppercase tracking-widest">+ Add New Address</span>
                  </div>
                </div>
              </div>
            )}
          </div>
        </div>
      </main>
      <Footer />
    </>
  );
}
